### ISSUE TITLE
Github workflows

### ISSUE THREAD

**Issue by andrehadianto** [Aztriltus/nextjs-ts-tailwind-template#10]
Should add github workflow for linting

**Comment by ayungavis** [comment]
There is a lint check in the GitHub workflow, you can see it [here](https://github.com/Aztriltus/nextjs-ts-tailwind-template/blob/557a85b8bbf09d7f670489c6abb581f90b99e752/.github/workflows/main.yml#L32) @andrehadianto

**Comment by andrehadianto** [comment]
oh, sorry totally missed that!
