### ISSUE TITLE
Eslint plugin

### ISSUE THREAD

**Issue by andrehadianto** [Aztriltus/nextjs-ts-tailwind-template#9]
Should also add `eslint-plugin-tailwindcss` and `eslint-plugin-simple-import-sort`

**Comment by Aztriltus** [comment]
Is there an issue with the import sort? I think I've added it 🤔 
 
https://github.com/Aztriltus/nextjs-ts-tailwind-template/blob/main/.eslintrc.js

**Comment by Aztriltus** [comment]
As for the tailwind one, what benefits do you enjoy from using it?

I saw the things it could do here https://www.npmjs.com/package/eslint-plugin-tailwindcss but not sure how much value it adds

**Comment by andrehadianto** [comment]
as for the import sort, turns out the GGP project didn't copy the hidden folders, resulting in `.vscode` settings to not be transferred and `fixOnSave` config to be turned off 🙏 

as for the tailwind plugin, i enjoy the auto sorting of the `classname`!

**Comment by Aztriltus** [comment]
Ah ok interesting. Let me try that. Thanks @andrehadianto for the recommendation

**Comment by Aztriltus** [comment]
@andrehadianto could you help to add this?

**Comment by sushanyadav** [comment]
let's use this:
https://github.com/tailwindlabs/prettier-plugin-tailwindcss

we used on Gridlock. thanks to @ayungavis
